version: '3'

networks:
  inception:
    driver: bridge

services:

  # Mandatory services
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    restart: on-failure
    networks:
      - inception
    env_file:
      - env.template
    volumes:
      - mariadb:/var/lib/mysql

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    restart: on-failure
    ports:
      - "443:443"
    networks:
      - inception
    env_file:
      - env.template



volumes:

  # Mandatory volumes
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      type: none
      device: ~/data/mariadb
      o: bind
