version: '3'

networks:
  inception:
    driver: bridge

services:

  # Mandatory services
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    restart: on-failure
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    restart: on-failure
    ports:
      - "443:443"
    networks:
      - inception
    env_file:
      - .env
    # depends_on:
    #   - wordpress
    # volumes:
    #   - wordpress:/var/www/html

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    restart: on-failure
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html

  # Bonus services
  static:
    build: ./requirements/bonus/static
    container_name: static
    image: static
    restart: on-failure
    ports:
      - "4242:4242"
    networks:
      - inception

  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    image: adminer
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - inception
    depends_on:
      - mariadb

volumes:

  # Mandatory volumes
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      type: none
      device: ~/data/mariadb
      o: bind

  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      type: none
      device: ~/data/wordpress
      o: bind
